apiVersion: v2
name: recurring-task-service
description: A Helm chart for the recurring-task-service

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "1.0.0"